apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: kagentic
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: ai-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: kagentic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: docker.io/library/kagentic-ai-agent:latest
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://kagentic:kagentic123@tool-registry:5432/tool_registry
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: api-key
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10 