apiVersion: v1
kind: Service
metadata:
  name: calculator-tool
  namespace: kagentic
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: calculator-tool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-tool
  namespace: kagentic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-tool
  template:
    metadata:
      labels:
        app: calculator-tool
    spec:
      containers:
      - name: calculator-tool
        image: docker.io/library/kagentic-calculator-tool:latest
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10 