apiVersion: v1
kind: Secret
metadata:
  name: search-api-credentials
  namespace: kagentic
type: Opaque
data:
  search-api-key: <base64-encoded-api-key>
---
apiVersion: v1
kind: Service
metadata:
  name: search-tool
  namespace: kagentic
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: search-tool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-tool
  namespace: kagentic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-tool
  template:
    metadata:
      labels:
        app: search-tool
    spec:
      containers:
      - name: search-tool
        image: docker.io/library/kagentic-web-search-tool:latest
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 5000
        env:
        - name: SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: search-api-credentials
              key: search-api-key
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10 